//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handle.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_BORROW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETAIL_BORROW()
        {
            this.PAYs = new HashSet<PAY>();
        }
    
        public string idDetailBorrow { get; set; }
        public string idBorrow { get; set; }
        public string idBook { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual BORROW BORROW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAY> PAYs { get; set; }
    }
}
