

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ManageLibrary.Database
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ManageLibraryEntities1 : DbContext
{
    public ManageLibraryEntities1()
        : base("name=ManageLibraryEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AUTHOR> AUTHORS { get; set; }

    public virtual DbSet<BOOK> BOOKS { get; set; }

    public virtual DbSet<BORROW> BORROWs { get; set; }

    public virtual DbSet<CARD> CARDS { get; set; }

    public virtual DbSet<CLASS> CLASSES { get; set; }

    public virtual DbSet<DETAIL_BORROW> DETAIL_BORROW { get; set; }

    public virtual DbSet<DETAIL_PAY> DETAIL_PAY { get; set; }

    public virtual DbSet<PAY> PAYs { get; set; }

    public virtual DbSet<PUBLISHER> PUBLISHERS { get; set; }

    public virtual DbSet<READER> READERS { get; set; }

    public virtual DbSet<TYPESOFBOOK> TYPESOFBOOKS { get; set; }

    public virtual DbSet<MANAGE_DECENTRALIZATION> MANAGE_DECENTRALIZATION { get; set; }

    public virtual DbSet<MANAGE_USER> MANAGE_USER { get; set; }

    public virtual DbSet<MANAGE_USERGROUP> MANAGE_USERGROUP { get; set; }

    public virtual DbSet<MANAGE_USERGROUP_USER> MANAGE_USERGROUP_USER { get; set; }

    public virtual DbSet<MONITOR> MONITORs { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

}

}

