
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ManageLibrary.Database
{

using System;
    using System.Collections.Generic;
    
public partial class DETAIL_BORROW
{

    public System.Guid idDetailBorrow { get; set; }

    public Nullable<System.Guid> idBorrow { get; set; }

    public Nullable<System.Guid> idBook { get; set; }

    public Nullable<int> status { get; set; }



    public virtual BOOK BOOK { get; set; }

    public virtual BORROW BORROW { get; set; }

}

}
