
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ManageLibrary.Database
{

using System;
    using System.Collections.Generic;
    
public partial class MANAGE_DECENTRALIZATION
{

    public string IdGroup { get; set; }

    public string IdMonitor { get; set; }

    public Nullable<bool> Licensed { get; set; }



    public virtual MANAGE_USERGROUP MANAGE_USERGROUP { get; set; }

    public virtual MONITOR MONITOR { get; set; }

}

}
