//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAY()
        {
            this.DETAIL_PAY = new HashSet<DETAIL_PAY>();
        }
    
        public System.Guid idPayCard { get; set; }
        public Nullable<System.DateTime> payDate { get; set; }
        public Nullable<int> numberPay { get; set; }
        public Nullable<System.Guid> idBorrow { get; set; }
    
        public virtual BORROW BORROW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_PAY> DETAIL_PAY { get; set; }
    }
}
