//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handle.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANAGE_USERGROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANAGE_USERGROUP()
        {
            this.MANAGE_DECENTRALIZATION = new HashSet<MANAGE_DECENTRALIZATION>();
            this.MANAGE_USERGROUP_USER = new HashSet<MANAGE_USERGROUP_USER>();
        }
    
        public string IdGroup { get; set; }
        public string NameGroup { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANAGE_DECENTRALIZATION> MANAGE_DECENTRALIZATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANAGE_USERGROUP_USER> MANAGE_USERGROUP_USER { get; set; }
    }
}
