//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handle.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAY()
        {
            this.DETAIL_BORROW = new HashSet<DETAIL_BORROW>();
        }
    
        public string idPayCard { get; set; }
        public Nullable<System.DateTime> payDate { get; set; }
        public Nullable<int> numberPay { get; set; }
        public string idBorrow { get; set; }
        public string idEmployees { get; set; }
    
        public virtual BORROW BORROW { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_BORROW> DETAIL_BORROW { get; set; }
    }
}
